# Project information
site_name: uvmcollab
site_author: Ciro Bermudez
site_description: >-
  uvmcollab is a comprehensive guide to SystemVerilog and UVM, providing
  templates, coding guidelines, and best practices for efficient verification.

# Copyright
copyright: >-
  Copyright &copy; 2025 uvmcollab

# Repository
repo_name: uvmcollab
repo_url: https://github.com/uvmcollab

# Configuration
theme:
  name: material
  language: en
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
    - navigation.sections
    - header.autohide
    - content.code.copy
  font:
    text: Inter
    code: Monaco
  favicon: assets/images/site_logo/favicon.svg
  logo: assets/images/site_logo/logo.svg

# Plugins
plugins:
  - search
 # - glightbox
 # - mkdocs-pdf

# Additional configuration
extra:
  generator: false
  social:
#  - icon: fontawesome/brands/gitlab
#    link: https://

# Custom stylesheets
extra_css:
  - stylesheets/extra.css

# Custom javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home:
    - index.md
  - SV:
    - sv/index.md
    - Basics:
      - sv/data-types.md
      - sv/clocking-blocks.md
      - sv/interfaces.md
      - sv/threads.md
  - UVM:
    - uvm/index.md
    - Guidelines:
      - uvm/guidelines/resource-guide.md
      - uvm/guidelines/coding-guidelines.md
    - FAQ:
      - uvm/faq/uvm_config_db.md
    - Templates:
      - uvm/templates/sequence-item.md
      - uvm/templates/sequencer.md
      - uvm/templates/driver.md
      - uvm/templates/monitor.md
      - uvm/templates/agent.md
      - uvm/templates/agent-config.md
      - uvm/templates/env.md
      - uvm/templates/env-config.md
      - uvm/templates/test.md
      - uvm/templates/sequence.md
      - uvm/templates/scoreboard.md
      - uvm/templates/coverage.md
      - uvm/templates/interface.md
    - Register Layer:
      - uvm/ral/register-layer.md
      - uvm/ral/register-model.md
      - uvm/ral/adapter.md
  - IP blocks:
    - ip-blocks/index.md
  - Skills:
    - skills/index.md
    - Git:
      - skills/git/git-basics.md
      - skills/git/git-ssh.md
      - skills/git/git-flow.md
    - Makefile:
      - skills/makefile/makefile-basics.md
    - Python:
      - skills/python/python-basics.md
  - Tools Guides:
    - tools-guides/index.md
    - Xilinx Vivado:
      - tools-guides/vivado/xvlog.md
      - tools-guides/vivado/xelab.md
      - tools-guides/vivado/xsim.md
  - Contacts:
    - contacts/index.md